defaults:
  - mppi: panda
  - isaacgym: normal

goal: [0.6, 0.0, 0.0, -1.875, 0, 1.875, 0]
render: true
n_steps: 1000
actors: ['panda', 'xaxis', 'yaxis']
initial_actor_positions: [[0.0, 0.0, 0.0]]

nx: 14
